
#general settings
[general]
	#Disable the anchors?
	disableAnchors = false
	#Disable the Muffle button in the player inventory?
	disableInventoryButton = true
	#Blacklisted Sounds - add the name of the sounds to blacklist, separated with comma
	forbiddenSounds = []

